### PR TITLE
Check commits instead of PR text for pull requests

### LINKED ISSUE #28: Check commits instead of PR text for pull requests
The tool should check the commits that are part of a PR instead of the PR text if it is executed for a pull request ([example run](https://github.com/admin-shell-io/aasx-package-explorer/actions/runs/161641055).

### PR DESCRIPTION
**Pull request by Fryuni**
- Closes #28

### CODE REVIEW

**Comment by Fryuni** [comment]
Here is the run on our repo showing how the failure is reported:

https://github.com/croct-tech/opinionated-commit-message/actions/runs/6710498865/job/18235816627

**Comment by mristin** [comment]
@Fryuni can you please rebase your branch so that we can re-run the CI?

**Comment by Fryuni** [comment]
@mristin rebased, and README updated

**Comment by mristin** [comment]
Thanks, @Fryuni! Should I release a minor version?

**Comment by Fryuni** [comment]
@mristin I'll try to implement the fix for merge commits today, if it works we can wait until that lands and release together.

If I find that it will take more time I'll ping you later so you can cut a release :)

**Pull request merged**
