### PR TITLE
Add more verbs scraped from another repository

### PR DESCRIPTION
**Pull request by faern**
We ran into more missing verbs. So I figured instead of adding them a
few at a time when we run into issues, let's investigate what we
actually have used historically and batch add them. I did the
following for our largest repository, this is the only place where we
currently enforce git commit message style with this action:
https://github.com/mullvad/mullvadvpn-app/.

I grabbed all the first words from the subject line of our commits:

```bash
git log --format=%s | \
    awk '{print tolower($1)}' | \
    tr -cd '\n[:alnum:]._-' | \
    sort -u > first-words
```

I then filtered out the ones not already in
`mostFrequentEnglishVerbs.ts`:

```bash
for word in $(cat first-words);
do
    if ! grep -x "  '$word'," mostFrequentEnglishVerbs.ts > /dev/null;
    then
        echo "$word";
    fi;
done
```

I then manually started going through the list of words. Many of them
are not even verbs, or verbs not in imperative form, since we have not
enforced this style before. But many of them are perfectly fine
imperative form verbs and I suggest they are added to this action.

I stopped at the letter D and decided to submit this PR. That's
because I was not sure if you wanted this addition or not, and
figured I should reach out for feedback before spending more time.
I'll likely continue the filtering anyway, and add it to a local
`path-to-additional-verbs` in case you don't want them upstream. But
having them upstream would be way more handy, since then we can easily
run this on multiple repositories without having to duplicate the verb
list.

Semi-related question: Does it make sense to separate
"Verbs specific to programming"?
I personally think that distinction is not very important.

### CODE REVIEW

**Comment by faern** [comment]
WHY does this enforce line length in PR *descriptions*? :joy: The formatting of PR descriptions are done by github. It renders fine without having limited line length.

**Comment by faern** [comment]
Fixed. But I had to make not-desired changes to my bash code to make it fit really :P

**Comment by faern** [comment]
I found in total 184 verbs that I initially classified as reasonable verbs to have. I have a PR up to add this as an additional wordlist to our own repository. But I would love if we could upstream as much as possible! When we want to start checking multiple repositories it would be really good if we did not have to maintain a separate wordlist or a fork of this action. https://github.com/mullvad/mullvadvpn-app/pull/5992

Tell me if you want this or not, so I know how to proceed :)

**Comment by mristin** [comment]
Hi @faern ! This is definitely a nice addition!

> Semi-related question: Does it make sense to separate
"Verbs specific to programming"?
I personally think that distinction is not very important.

No, not at this scale. Feel free to re-order the verbs alphabetically.

You can go ahead and add all the verbs -- I can quickly skim through the list to check that all of them are actually verbs so that nothing slips. Just ping me once I should review.

**Comment by faern** [comment]
Awesome! I'm glad to hear that. I have now pushed all our words! The first commit just adds our additional words. The second commit removes the distinction between "normal" and programmer verbs and sorts the list, so it's mostly automatically generated noise. Probably easiest to review the PR per commit.

**Comment by faern** [comment]
@mristin Ping ;) This wordlist has passed internal review in my team, so it's already partially sanity checked. I hope you will like it.

One question that did pop up was whether or not abbreviations such as `init` and `dedup` should be in the list or not. I left them in since I felt they are very common programmer abbreviations for imperative verbs. But I can remove them if you think otherwise.

**Comment by mristin** [comment]
Thanks a lot, @faern ! Please let me know when I should publish a new patch version.

**Comment by faern** [comment]
Awesome, thank you! Having a release would be amazing. I mean, I can't promise I won't come with more words in the coming few days also, but currently we could really use these 185 extra verbs :P

**Comment by faern** [comment]
I'm not fluent in github actions. When I depend on this action, does it actually run the code in the `dist/` directory? Because I tried depending on the commit hash for the `master` branch on this repo now, but it still does not accept "Source" as an OK verb. 

```
uses: mristin/opinionated-commit-message@623037eb118a24335513cd7c4b2d4adabf292a8d
```

**Pull request merged**
