### PR TITLE
Add "restart" and "coalesce" as allowed verbs

### PR DESCRIPTION
**Pull request by faern**
Thank you for this very handy action!

Just a few days after introducing it on our repository we had
developers requesting these two extra verbs.
I explicitly [added them to our repo].
But they are not weird verbs, so I don't see any
reason why they could not be upstreamed also.

[added them to our repo]: https://github.com/mullvad/mullvadvpn-app/pull/5975

### CODE REVIEW

**Review by Fryuni — COMMENTED** [review]
LGTM

**Comment by mristin** [comment]
@faern sorry, I edited the PR description since the CI failed only to realize that the CI works on commit messages and not on the pull request description 🤦‍♂️.

Can you please re-flow the commit message to fit 72 characters in width, with links put at the end of the message on separate lines, and referenced from the text? Finally, you have to force-push the ammended message as we check for all the commit messages in a PR.

**Comment by faern** [comment]
The commit message is just a short oneliner... But I added a body now since it looks like you enforce that... But the failure log was about the PR description being too long lines, so I edited that *also*... Now it might work?

**Comment by mristin** [comment]
Thanks, @faern ! Merged in! Do you need a patch version?

**Comment by faern** [comment]
We are not in a hurry since we added them as extra verbs for now. Release whenever you want to ☺️

**Comment by faern** [comment]
Maybe we realize even more words in a few days, who knows ;)

**Pull request merged**
