### PR TITLE
Add 'bias', 'obfuscate' and 'tidy'

### PR DESCRIPTION
**Pull request by faern**
Another small batch of allowed verbs that we have ended up using since adopting this CI check! Following in the footsteps of #130 and #131 :)

### CODE REVIEW

**Review by mristin — APPROVED** [review]
Thanks, @faern !

**Comment by mristin** [comment]
@faern can you please fix the commit message? (See the failing CI.)

**Comment by faern** [comment]
@mristin 

> @faern can you please fix the commit message? (See the failing CI.)

I already have... Please check the commits tab. I dunno why the CI did not re-run

**Comment by faern** [comment]
I recommited the same thing and force pushed, just to trigger the CI. Should be fine now?

**Comment by faern** [comment]
Oh, lol. It was complaining about the length of the github PR title? :joy: My god. I have been so confused about that before.

Why do you enforce *that* to be so short? I guess that's a more ideological question. The only reason I want to limit the length of git commit messages is so they display nicely when rendered as a tree in my terminal. For the github PR title and description none of those limitations apply.

**Comment by mristin** [comment]
> Why do you enforce that to be so short?

I think I couldn't really separate the two in the code as far as I can remember. I'm open to changing that behavior -- please feel free to open a new issue!

**Comment by faern** [comment]
But we are using this CI action and only limit git commit messages, not github PR content. It just works? :shrug: :joy: 
https://github.com/mullvad/mullvadvpn-app/blob/main/.github/workflows/git-commit-message-style.yml#L25-L35

**Comment by faern** [comment]
However, that is completely unrelated to this PR. Feel free to merge the extra verbs :)

**Comment by mristin** [comment]
> But we are using this CI action and only limit git commit messages, not github PR content. It just works? 🤷 😂 https://github.com/mullvad/mullvadvpn-app/blob/main/.github/workflows/git-commit-message-style.yml#L25-L35

I think the event is crucial -- if you run it against pull request, the body will be the pull request description. I'm not really sure anymore, though.

**Pull request merged**
